iskurMVC_Eticaret/Controllers/LogController.cs
using iskurMVC_Eticaret.Models;
using iskurMVC_Eticaret.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace iskurMVC_Eticaret.Controllers
{
    public class LogController : Controller
    {
        UserService userService;
        public LogController()
        {
            userService = new UserService();
        }
        // GET: Log
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(CreateAccountModel accountModel)
        {
            var user = userService.InsertUser(accountModel);
            if (user != null)
            {
                LoginModel loginModel = new LoginModel()
                {
                    UserID = user.UserID,
                    UserName = user.UserName,
                    Password = user.Password
                };
                Session["Role"] = "User";
                Session["User"] = loginModel;
                return RedirectToAction("Index", "Main");
            }
            else
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginModel loginModel)
        {
            var user = userService.UserLogin(loginModel);
            if (user != null)
            {
                Session["User"] = user;
                Session["Role"] = "User";
                return RedirectToAction("Index", "Main");
            }
            else
            {
                return View();
            }
        }
        public ActionResult Exit()
        {
            Session.Remove("User");
            Session.Remove("Role");
            return RedirectToAction("Index", "Main");
        }
    }
}

iskurMVC_Eticaret/Views/Log/Create.cshtml
@using iskurMVC_Eticaret.Models
@model CreateAccountModel


@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Create", "Log"))
{
    <div class="container">
        <div class="col-lg-4"><h2>Login</h2></div>
        <div class="form-group col-lg-4">
            @Html.LabelFor(x => x.UserName)
            @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
        </div>
        <div class="form-group col-lg-4">
            @Html.LabelFor(x => x.Password)
            @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
        </div>
        <div class="form-group col-lg-4">
            @Html.LabelFor(x => x.Phone)
            @Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
        </div>
        <div class="form-group col-lg-4">
            @Html.LabelFor(x => x.EMail)
            @Html.TextBoxFor(x => x.EMail, new { @class = "form-control" })
        </div>
        <div class="col-lg-4">
            <button type="submit" class="btn btn-success">Üye Ol</button>
        </div>
    </div>
}

iskurMVC_Eticaret/Views/Log/Login.cshtml
@using iskurMVC_Eticaret.Models
@model LoginModel


@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}



@using (Html.BeginForm("Login", "Log"))
{
    <div class="container">

        <div class="col-lg-4"><h2>Login</h2></div>
        <div class="form-group col-lg-4">
            @Html.LabelFor(x => x.UserName)
            @Html.TextBoxFor(x => x.UserName, new { @class = "form-control password" })
        </div>
        <div class="form-group col-lg-4">
            @Html.LabelFor(x => x.Password)
            @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
        </div>
        <div class="col-lg-4">
            <button type="submit" class="btn btn-success">Giriş Yap</button>
        </div>
    </div>
}